# action.yml
name: 'Localtunnel forwarding'
description: 'Provides a localtunnel exposed HTTP endpoint'
inputs:
  webserver-host:
    description: 'Docker/internal IP or Host name that serves web content'
    required: true
    default: 'drupal_container'
  webserver-port:
    description: 'Docker/internal port that serves web content'
    required: true
    default: '80'
runs:
  using: 'docker'
  image: 'docker://efrecon/localtunnel'
  args:
    - --port ${{ inputs.webserver-port }}
    - --local-host ${{ inputs.webserver-host }}
